version: '3'
services:
  backend:
    build: ./backend
    ports:
      - '5000:5000'
    environment:
      - NODE_ENV=production
    volumes:
      - ./backend:/app
    depends_on:
      - frontend

  frontend:
    build: ./frontend/chatbot-frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend/chatbot-frontend:/app